# chewie server config

server:
    address: 127.0.0.1
    partition_port: 21001
    data_port: 21001
  
log:
    path: /megawise/logs/chewie
    level: 0                    # optional: trace = 0, debug = 1, info = 2, warn = 3, error = 4, critical = 5, off = 6
    rotating: yes               # yes means rotated log, no means non-rotated log;
    rotating_size_limit: 64     # 64 MB, valid when rotating is yes
    rotating_number_limit: 10   # valid when rotating is yes


# self defined syntax, need to run script to load cache_conf
# syntax is "import <filename>" in comments
#import cache_conf
cache:  # size in GB
    cpu:
        physical_memory: 12
        partition_memory: 12
    
    gpu:
        gpu_num: 1
        physical_memory: 2 
        partition_memory: 2


# which device will be selected if multi victim exist
advice_copy_from: cpu           # options: cpu / gpu
